camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    deployment-resource-pattern:
      - classpath*:**/*.bpmn
      - classpath*:**/*.form
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
spring:
  datasource:
    url: jdbc:postgresql://localhost/camundabpmn
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true