camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    deployment-resource-pattern:
      - classpath*:**/*.bpmn
      - classpath*:**/*.form
spring.mvc.pathmatch.matching-strategy: ant_path_matcher